bibentry(bibtype = "TechReport",
         key = "Leisch+Weingessel+Hornik:1998",
         author = c(person(given = "Friedrich",
                           family = "Leisch",
                           comment = c(ORCID = "0000-0001-7278-1983")),
                    person(given = "Andreas",
                           family = "Weingessel"),
                    person(given = "Kurt",
                           family = "Hornik",
                           comment = c(ORCID = "0000-0003-4198-9911"))),
         title = "On the Generation of Correlated Artificial Binary Data",
         institution = "SFB Adaptive Information Systems and Modelling in Economics and Management Science, WU Vienna University of Economics and Business",
         .url = "http://epub.wu.ac.at/id/eprint/286",
         doi = "10.57938/6884f809-93bc-4497-ab2b-fc1611198f5b",
         year = "1998",
         month = "June",
         number = "13",
         type = "Working Paper")
